# Generated by Django 5.2.4 on 2025-08-01 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='balance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Баланс пользователя',
                'verbose_name_plural': 'Балансы пользователей',
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='BalanceOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('deposit', 'Пополнение'), ('withdraw', 'Списание'), ('transfer_in', 'Перевод на счет'), ('transfer_out', 'Перевод со счета')], max_length=20)),
                ('operation_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('operation_result', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='balance.balance')),
                ('related_balance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_operations', to='balance.balance')),
            ],
            options={
                'verbose_name': 'Операция с балансом',
                'verbose_name_plural': 'Операции с балансом',
                'ordering': ['-created_at'],
            },
        ),
    ]
